### ISSUE TITLE
Wrong PROG settings when using the Ant task

### ISSUE THREAD

**Issue by alexsturm** [craigwblake/redline#84]
Hi, 

when using the Ant task, the (PRE|POST|...)(IN|UN|...)PROG setting is always set to "/bin/sh" regardless of what is defined in the script itself (e.g. #!/bin/bash).

The "Builder" class reads the script interpreter from the script interpreter correctly, but the task resets it to the default value afterwards.

See https://github.com/craigwblake/redline/blob/master/src/main/java/org/redline_rpm/ant/RedlineTask.java#L135 for an example.

What is the reason for resetting the interpreter program in the task? Ideally (from my point of view) the task would just leave the program as it is.

Thanks,
Alex

**Comment by p120ph37** [comment]
On May 7, 2009 as part of ed101ad7812f639c8c422a2cadb34202158894a0, `RedlineTask.java` support for scripts was added, and `Builder.java`'s support for scripts was extended to read and use the shebang line.

On June 24, 2012, @deckrider committed 0314e0b14daf6646d7d08065cd911d9941631627 with the primary purpose of enhancing the `Builder.set*Program()` methods to assume a default interpreter of `/bin/sh` if called with a null or empty-string argument.  This is also the point at which the `Builder.set*Program( "");` statements were added to `RedlineTask.java`.

I'm guessing this was not intentional - @deckrider may have simply overlooked the fact that `Builder.set*Program()` was already being called from inside `Builder.set*Script()` and assumed he needed to add an explicit call to it in `RedlineTask.java` in order to take advantage of the default-interpreter code he had just added.

**Comment by deckrider** [comment]
I probably did overlook it.
